### ISSUE TITLE
Undefined Array Key "financial_type_id"

### ISSUE THREAD

**Issue by bmango** [Kin-Coop/kin-civicrm-ext#2]
I'm getting the following notification every time the Civi cron task runs:

`[PHP Warning] Undefined array key "financial_type_id" at /home/kin/sites/kin/dir/web/sites/default/files/civicrm/ext/kincoop/kincoop.php:23`

**Comment by bmango** [comment]
Have commited an update to add a check that 'financial_type_id' is set - [f1fa034](https://github.com/Kin-Coop/kin-civicrm-ext/commit/f1fa034853b49bd2180d9121744809a659a970bf) #2

**Comment by bmango** [comment]
@rjferrier Do you want to check if my update is ok?

**Comment by rjferrier** [comment]
Thanks @bmango. If it fixes it, then that's fine. I see you've committed to main. I might refactor it a little at some point.

Maybe we need an automated test suite after all!
